#! /bin/bash

export VERSION="46"
export SYSTEM_DESC="ChimeraOS"
export SYSTEM_NAME="chimeraos"
export USERNAME="gamer"
export SIZE="12000MB"
export ARCHIVE_DATE=$(date -d 'yesterday' +%Y/%m/%d)
export WEBSITE="https://chimeraos.org"
export DOCUMENTATION_URL="https://chimeraos.org/about"
export BUG_REPORT_URL="https://github.com/ChimeraOS/chimeraos/issues"

export KERNEL_PACKAGE="linux-chimeraos"
export KERNEL_PACKAGE_ORIGIN="local"

export PACKAGES="\
	accountsservice \
	acpi_call-dkms \
	alsa-firmware \
	alsa-utils \
	amd-ucode \
	bash-completion \
	bluedevil \
	breeze-gtk \
	broadcom-wl-dkms \
	bzip2 \
	cifs-utils \
	cpupower \
	diffutils \
	dkms \
	discover \
	distrobox \
	dmidecode \
	dosbox \
	dolphin \
	dolphin-plugins \
	efibootmgr \
	epiphany \
	ethtool \
	evtest \
	expect \
	exfatprogs \
	falkon \
	fcitx5-im \
	fcitx5-chinese-addons \
	fcitx5-pinyin-zhwiki \
	ffmpeg \
	file \
	ffmpegthumbnailer \
	firejail \
	flatpak \
	flatpak-kcm \
	fmt \
	fuse-zip \
	fuse2 \
	fwupd \
	git \
	grml-zsh-config \
	gst-plugin-pipewire \
	gvfs-smb \
	gvfs-nfs \
	gzip \
	haveged \
	htop \
	intel-gpu-tools \
	intel-media-driver \
	intel-ucode \
	intel-undervolt \
	jq \
	kate \
	kde-gtk-config \
	kdeconnect \
	kdeplasma-addons \
	kfind \
	kgamma \
	kinfocenter \
	konsole \
	kpipewire \
	kscreen \
	ksshaskpass \
	kwallet-pam \
	less \
	lib32-curl \
	lib32-fontconfig \
	lib32-freetype2 \
	lib32-libgpg-error \
	lib32-libnm \
	lib32-libxinerama \
	lib32-libxcrypt-compat \
	lib32-libva \
	lib32-libva-intel-driver \
	lib32-libva-vdpau-driver \
	lib32-openal \
	lib32-pipewire \
	lib32-systemd \
	lib32-vulkan-icd-loader \
	libcurl-gnutls \
	libidn11 \
	libretro-beetle-pce-fast \
	libretro-beetle-psx-hw \
	libretro-citra \
	libretro-desmume \
	libretro-dolphin \
	libretro-flycast \
	libretro-genesis-plus-gx \
	libretro-kronos \
	libretro-mesen-s\
	libretro-mgba \
	libretro-mupen64plus-next \
	libretro-nestopia \
	libretro-picodrive \
	libretro-ppsspp \
	libretro-shaders-slang \
	libretro-snes9x \
	libva-intel-driver \
	libva-vdpau-driver \
	libxcrypt-compat \
	libxss \
	lightdm \
	linux-firmware \
	liquidctl \
	logrotate \
	lrzip \
	loupe \
	lshw \
	mesa-demos \
	modemmanager \
	nano \
	networkmanager \
	nfs-utils \
	noto-fonts-emoji \
	nss-mdns \
	onboard \
	openal \
	openssh \
	p7zip \
	pipewire \
	pipewire-alsa \
	pipewire-jack \
	pipewire-pulse \
	plasma-browser-integration \
	plasma-desktop \
	plasma-disks \
	plasma-nm \
	plasma-pa \
	plasma-thunderbolt \
	plasma-vault \
	plasma-wayland-session \
	podman \
	pulsemixer \
	python \
	python-inotify-simple \
	qtractor \
	retroarch \
	rsync \
	smbclient \
	sof-firmware \
	sshfs \
	steam \
	sudo \
	tar \
	tree \
	ttf-liberation \
	unace \
	unrar \
	unzip \
	usb_modeswitch \
	usbutils \
	vim \
	vulkan-icd-loader \
	wavpack \
	wget \
	which \
	wireplumber \
	wqy-microhei \
	xdg-desktop-portal \
	xdg-desktop-portal-gtk \
	xdg-desktop-portal-kde \
	xdg-desktop-portal-wlr \
	xdg-user-dirs-gtk \
	xf86-video-amdgpu \
	xorg-server \
	xorg-server-xvfb \
	xorg-xinit \
	xsettingsd \
	xz \
	zip \
	zsh \
	zsh-autosuggestions \
	zsh-completions \
	zsh-syntax-highlighting \
"

export PACKAGE_OVERRIDES="\
	https://github.com/ChimeraOS/linux-chimeraos/releases/download/v6.8-chos1-1/linux-chimeraos-6.8.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/linux-chimeraos/releases/download/v6.8-chos1-1/linux-chimeraos-headers-6.8.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.0.4-chos1-1/lib32-libva-mesa-driver-1--24.0.4.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.0.4-chos1-1/lib32-mesa-1--24.0.4.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.0.4-chos1-1/lib32-mesa-vdpau-1--24.0.4.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.0.4-chos1-1/lib32-opencl-rusticl-mesa-1--24.0.4.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.0.4-chos1-1/lib32-vulkan-intel-1--24.0.4.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.0.4-chos1-1/lib32-vulkan-mesa-layers-1--24.0.4.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.0.4-chos1-1/lib32-vulkan-radeon-1--24.0.4.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.0.4-chos1-1/lib32-vulkan-swrast-1--24.0.4.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.0.4-chos1-1/libva-mesa-driver-1--24.0.4.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.0.4-chos1-1/mesa-1--24.0.4.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.0.4-chos1-1/mesa-vdpau-1--24.0.4.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.0.4-chos1-1/opencl-rusticl-mesa-1--24.0.4.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.0.4-chos1-1/vulkan-intel-1--24.0.4.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.0.4-chos1-1/vulkan-mesa-layers-1--24.0.4.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.0.4-chos1-1/vulkan-radeon-1--24.0.4.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.0.4-chos1-1/vulkan-swrast-1--24.0.4.chos1-1-x86_64.pkg.tar.zst \
	https://archive.archlinux.org/repos/2023/06/28/extra/os/x86_64/libretro-pcsx2-11900-2-x86_64.pkg.tar.zst \
	https://archive.archlinux.org/packages/l/libretro-mame/libretro-mame-85763-1-x86_64.pkg.tar.zst \
	https://steamdeck-packages.steamos.cloud/archlinux-mirror/jupiter-main/os/x86_64/steamdeck-kde-presets-0.21-1-any.pkg.tar.zst \
"

# Each entry is the clone url (https://aur.archlinux.org/{AUR_PACKAGE}.git)
# Which is often the same as the package name but it can be different.
# Check on the AUR webpage if you are unsure
export AUR_PACKAGES="\
	asusctl \
	antimicrox \
	ayaneo-platform-dkms-git \
	ayn-platform-dkms-git \
	bcm20702a1-firmware \
	bmi260-dkms \
	boxtron \
	chimera \
	chimeraos-device-quirks-git \
	downgrade \
	evdev-keepalive \
	frzr \
	gamescope-session-steam-git \
	gamescope-session-steam-plus-git \
	hhd \
	hhd-user \
	hhfc-git \
	legendary \
	lib32-gamescope-plus \
	lib32-gperftools \
	libretro-dosbox-pure-git \
	libretro-opera-git \
	libretro-prosystem-git \
	libretro-stella2014-git \
	libretro-virtualjaguar-git \
	kanit-font \
	nintendo-udev \
	opengamepadui-bin \
	opengamepadui-session-git \
	powerstation-bin \
	protonup-qt-bin \
	python-vdf \
	r8152-dkms \
	retroarch-autoconfig-udev-git \
	rtl8812au-dkms-git \
	rtl8814au-dkms-git \
	rtl88x2bu-dkms-git \
	rtl8821au-dkms-git \
	ryzenadj-git \
	steam_notif_daemon \
	steam-removable-media-git \
	wyvern \
	waydroid \
	waydroid-script-git \
	yay-bin \
	zenergy-dkms-git \
"

export SERVICES="\
	NetworkManager \
	avahi-daemon \
	bluetooth \
	bluetooth-workaround \
	fstrim.timer \
	haveged \
	home-swapfile.swap \
	lightdm \
	powerstation \
	sshd \
	systemd-timesyncd \
	swapfile \
	waydroid-container \
"

export USER_SERVICES="\
	chimera.service \
	pipewire \
	steam-patch.service \
"

export FILES_TO_DELETE="\
	/boot/initramfs-linux-fallback.img \
	/usr/share/SFML \
	/usr/share/doc \
	/usr/share/gtk-doc \
	/usr/share/help \
	/usr/share/libretro/autoconfig/udev/Gasia_PS_Gamepad_USB.cfg \
	/usr/share/libretro/autoconfig/udev/Sony-PlayStation3-DualShock3-Controller-Bluetooth.cfg \
	/usr/share/libretro/autoconfig/udev/Xbox_360_Wireless_Receiver_Chinese01.cfg \
	/usr/share/man \
"

postinstallhook() {
	# Add sudo permissions
	sed -i '/%wheel ALL=(ALL:ALL) ALL/s/^# //g' /etc/sudoers
	echo "${USERNAME} ALL=(ALL) NOPASSWD: /usr/bin/dmidecode -t 11
	" >/etc/sudoers.d/steam
	echo "${USERNAME} ALL=(ALL) NOPASSWD: /usr/bin/chimera-session-use-gamescope
	${USERNAME} ALL=(ALL) NOPASSWD: /usr/bin/chimera-session-use-lightdm
	${USERNAME} ALL=(ALL) NOPASSWD: /usr/share/chimera/bin/power-tool
	" >/etc/sudoers.d/chimera

	# disable retroarch menu in joypad configs
	find /usr/share/libretro/autoconfig -type f -name '*.cfg' | xargs -d '\n' sed -i '/input_menu_toggle_btn/d'

	# download and add racing wheel udev rules
	pushd /usr/lib/udev/rules.d
	curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-fanatec-wheel-perms.rules
	curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-logitech-wheel-perms.rules
	curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-thrustmaster-wheel-perms.rules
	popd

	# Remove build tools for slimmer image
	rm /usr/share/libalpm/hooks/70-dkms-install.hook
	rm /usr/share/libalpm/hooks/70-dkms-upgrade.hook
	rm /usr/share/libalpm/hooks/71-dkms-remove.hook
	pacman --noconfirm -Rnsdd make gcc dkms ${KERNEL_PACKAGE}-headers

	# remove dolphin standalone emulator files (only need /usr/share/dolphin-emu/sys)
	rm /usr/bin/dolphin-emu
	rm /usr/bin/dolphin-emu-nogui
	# dolphin-tool is no longer created in new builds?
	#rm /usr/bin/dolphin-tool
	rm /usr/share/applications/dolphin-emu.desktop

	# clean up desktop shortcuts
	sed -i -e 's/Name=Steam (Runtime)/Name=Steam/' /usr/share/applications/steam.desktop

	# force -steamdeck option in desktop mode to prevent constant steam updates
	sed -i 's,Exec=/usr/bin/steam-runtime,Exec=/usr/bin/steam-runtime -steamdeck,' /usr/share/applications/steam.desktop

	# set permissions for intel_gpu_top and mangohud
	setcap cap_perfmon=+ep /usr/bin/intel_gpu_top
}
