#! /bin/bash

export SIZE="10GB"

export PACKAGES="\
	htop \
	lightdm \
	accountsservice \
	xorg-server \
	bluez \
	bluez-utils \
	lib32-freetype2 \
	lib32-curl \
	lib32-libgpg-error \
	ttf-dejavu \
	networkmanager \
	pulseaudio \
	lib32-libpulse \
	pulseaudio-alsa \
	sudo \
	python \
	steam \
	retroarch \
	retroarch-assets-xmb \
	libretro-beetle-psx \
	libretro-beetle-psx-hw \
	libretro-blastem \
	libretro-bsnes \
	libretro-citra \
	libretro-desmume \
	libretro-gambatte \
	libretro-genesis-plus-gx \
	libretro-melonds \
	libretro-mgba \
	libretro-mupen64plus \
	libretro-nestopia \
	libretro-parallel-n64 \
	libretro-ppsspp \
	libretro-redream \
	libretro-reicast \
	libretro-scummvm \
	libretro-snes9x \
	libretro-yabause \
	dolphin-emu \
	flatpak \
	vulkan-icd-loader \
	lib32-vulkan-icd-loader \
	libva-mesa-driver \
	lib32-libva-mesa-driver \
	mesa-vdpau \
	lib32-mesa-vdpau \
	vulkan-radeon \
	lib32-vulkan-radeon \
	xf86-video-amdgpu \
"

export AUR_PACKAGES="\
	frzr \
	steamos-compositor-plus \
	cemu \
"

export SERVICES="\
	frzr-autoupdate \
	NetworkManager \
	lightdm \
	bluetooth \
"
